In [1]:
import pandas as pd
from datetime import timedelta
import datetime as dt
import json
import os
import glob
import numpy as np

In [2]:
# declare source directory/paths
current_dir = os.getcwd()
parent_dir = os.path.dirname(current_dir)
prices_dir = os.path.join(parent_dir,'stock_scrape_load','data')

prices_path = f"{prices_dir}/*.json"
names_path = os.path.join(parent_dir,'05_michael_test/company_info.csv')
history_path = os.path.join(parent_dir,'05_michael_test','stock_data2.json')

In [3]:
# declare empty list to store data
data = []
past_history = []

# Loop through all json files and update data list
for file in glob.glob(prices_path):
    with open(file, 'r') as json_prices:
        json_prices_data = json.load(json_prices)
        data.append(json_prices_data)

for file in glob.glob(history_path):
    with open(file, 'r') as json_history:
        json_history_data = json.load(json_history)
        past_history.append(json_history_data)

# Create company name / ticker symbol Dataframe
names_df = pd.read_csv(names_path)
names_df = names_df[['ticker','shortName']]

# Create hitorical prices Dataframe
prices_df = pd.concat([pd.DataFrame(d) for d in data], ignore_index = True)
prices_df['date'] = pd.to_datetime(prices_df['date'])
prices_df = prices_df.replace(np.nan, None)
past_history = pd.DataFrame(pd.read_json(history_path)).drop(columns='Adj Close')
past_history = pd.merge(past_history,names_df,how = 'left', on = 'ticker')



# View that sweet sweet extended dataframe!
# prices_df = prices_df.sort_values(['ticker','date'])
past_history.head(20)

,Date,Open,High,Low,Close,Volume,ticker,shortName
0,2023-07-03,193.779999,193.880005,191.759995,192.460007,31458200,AAPL,Apple Inc.
1,2023-07-05,191.570007,192.979996,190.619995,191.330002,46920300,AAPL,Apple Inc.
2,2023-07-06,189.839996,192.020004,189.199997,191.809998,45094300,AAPL,Apple Inc.
3,2023-07-07,191.410004,192.669998,190.240005,190.679993,46778000,AAPL,Apple Inc.
4,2023-07-10,189.259995,189.990005,187.039993,188.610001,59922200,AAPL,Apple Inc.
5,2023-07-11,189.160004,189.300003,186.600006,188.080002,46638100,AAPL,Apple Inc.
6,2023-07-12,189.679993,191.699997,188.470001,189.770004,60750200,AAPL,Apple Inc.
7,2023-07-13,190.500000,191.190002,189.779999,190.539993,41342300,AAPL,Apple Inc.
8,2023-07-14,190.229996,191.179993,189.630005,190.690002,41573900,AAPL,Apple Inc.
9,2023-07-17,191.899994,194.320007,191.809998,193.990005,49798987,AAPL,Apple Inc.
10,2023-07-03,339.190002,340.899994,336.570007,337.989990,12508700,MSFT,Microsoft Corporation
11,2023-07-05,335.089996,341.649994,334.730011,338.149994,18172400,MSFT,Microsoft Corporation
12,2023-07-06,337.299988,342.989990,335.500000,341.269989,28161200,MSFT,Microsoft Corporation
13,2023-07-07,339.320007,341.790009,337.000000,337.220001,21185300,MSFT,Microsoft Corporation
14,2023-07-10,334.600006,335.230011,327.589996,331.829987,32791400,MSFT,Microsoft Corporation
15,2023-07-11,331.059998,332.859985,327.000000,332.470001,26698200,MSFT,Microsoft Corporation
16,2023-07-12,336.600006,341.649994,335.670013,337.200012,29995300,MSFT,Microsoft Corporation
17,2023-07-13,339.559998,343.739990,339.019989,342.660004,20567200,MSFT,Microsoft Corporation
18,2023-07-14,347.589996,351.429993,344.309998,345.239990,28302200,MSFT,Microsoft Corporation
19,2023-07-17,345.678009,346.959991,342.200012,345.730011,20023516,MSFT,Microsoft Corporation

In [4]:
prices_df.head()

,ticker,date,sector,52WeekChange,ask,bid,52WeekHigh,52WeekLow,dailyOpen,previousClose,dailyVolume,quickRatio,10DayAverageVolume,marketCap,dayHigh,dayLow
0,AAPL,2023-07-11,Technology,29.273487,188.24,188.12,194.48,124.17,189.16,188.61,46509718.0,0.764,51012280.0,2958253883392.0,None,None
1,MSFT,2023-07-11,Technology,31.556665,332.57,332.52,351.47,213.43,331.06,331.83,26635569.0,1.655,22791880.0,2472077426688.0,None,None
2,GOOG,2023-07-11,Communication Services,4.923034,117.71,117.65,129.55,83.45,116.76,116.87,17940869.0,2.195,21102290.0,1491679969280.0,None,None
3,AMZN,2023-07-11,Consumer Cyclical,16.648556,128.93,128.87,146.57,81.43,127.75,127.13,49842486.0,0.689,45253080.0,1321334341632.0,None,None
4,NVDA,2023-07-11,Technology,179.64258,424.22,423.77,439.9,108.13,424.81,421.8,28118201.0,2.672,37582070.0,1047403495424.0,None,None

In [5]:
# symbol = 'CAT'

# row = prices_df.loc[prices_df['ticker'] == symbol]
# print(row)

In [6]:
# def get_closing_date(row):
#     reported_day = row['date']
#     actual_close_day = row['datePrevClose']

#     if reported_day.weekday() == 0: # When the previous day is Monday
#         actual_close_day -= timedelta(days=2) # now it is Friday

#     if pd.isnull(actual_close_day): # Check if actual_close_day is NaT
#         actual_close_day = row['date'] - timedelta(days=1) # Fill with yesterday's date

#     return actual_close_day # provide the date of the most recent Friday

# prices_df['datePrevClose'] = prices_df['date'].shift(1) # Create new column, and locate it next to the current prices date
# prices_df['datePrevClose'] = prices_df.apply(get_closing_date, axis=1)
# prices_df['dailyClose'] = prices_df['previousClose'].shift(-1)

# prices_df.head(18)

In [7]:
# # Pick out the columns I want included in final json
# ticker = pd.DataFrame(prices_df[['ticker','date','dailyOpen','dayHigh', 'dayLow','previousClose','dailyVolume']])
# ticker = ticker.rename(columns = {'date':'Date',
#                                   'dailyOpen': 'Open',
#                                   'dayHigh' : 'High',
#                                   'dayLow': 'Low', 
#                                   'previousClose': 'Close',
#                                   'dailyVolume':'Volume'
# })

# ticker = pd.merge(ticker,past_history, how = 'left', on = 'Date')

# complete_df = pd.merge(ticker, names_df, how = 'left', on = 'ticker')
print(f"There are {len(past_history.value_counts(['Date']))} days of data represented")
# ticker.head(25)

There are 10 days of data represented

In [8]:
past_history.groupby(['shortName']).value_counts()

shortName    Date        Open        High        Low         Close       Volume    ticker
AT&T Inc.    2023-07-03  15.950000   16.120001   15.950000   16.120001   18424200  T         1
             2023-07-05  16.080000   16.230000   16.000000   16.070000   32988100  T         1
             2023-07-06  16.010000   16.030001   15.840000   15.870000   33325300  T         1
             2023-07-07  15.540000   15.750000   15.530000   15.610000   28987000  T         1
             2023-07-10  15.520000   15.550000   15.220000   15.270000   45305500  T         1
                                                                                            ..
Zoetis Inc.  2023-07-11  170.539993  171.460007  169.460007  170.139999  1081300   ZTS       1
             2023-07-12  171.949997  173.089996  170.509995  171.860001  1471800   ZTS       1
             2023-07-13  172.410004  172.970001  170.940002  171.000000  1001500   ZTS       1
             2023-07-14  171.660004  173.369995  171.119995  172.190002  2455900   ZTS       1
             2023-07-17  172.520004  172.520004  169.679993  170.729996  1634187   ZTS       1
Length: 1000, dtype: int64

In [11]:
historical_json = []
grouped_tickers = past_history.groupby(['ticker'])
grouped_dates = past_history.groupby(['Date'])
grouped_companies = past_history.groupby(['shortName'])
data = {
    "tickers": list(grouped_tickers.groups.keys()),
    "companies":list(grouped_companies.groups.keys()),
    "dates": list(grouped_dates.groups.keys()),
    "history": []
}

for ticker, group in grouped_tickers:
    for index, row in group.iterrows():
        ticker_data = {
            "ticker": ticker,
            "name": row['shortName'],
            "date": row['Date'],
            "values": [{
                "date": row['Date'],
                "previousClose": row['Close'],
                "dailyOpen": row['Open'],
                "dayHigh": row['High'],
                "dayLow": row['Low'],
                # "ask": row['ask'],
                # "bid": row['bid'],
                "volume": row['Volume']
            }]
        }
        data["history"].append(ticker_data)

# json cannot work with datetime dtypes: https://www.geeksforgeeks.org/how-to-fix-datetime-datetime-not-json-serializable-in-python/
def serialize_dt(obj):
    if isinstance(obj, dt.datetime):
        return obj.isoformat()
    # elif isinstance(obj, float) and np.isnan(obj):
    #     return None  # Convert NaN to null
    raise TypeError("Type not serializable")

# Write json to 'visualizations' directory
json_data = json.dumps(data, indent=4, default = serialize_dt) #, cls = CustomEncoder)
with open("../visualizations/historical.json", "w") as json_file:
    json_file.write(json_data)

In [8]:
#------------------------------
#--Archive snippets below------
#------------------------------

# class CustomEncoder(json.JSONEncoder):
#     def default(self, obj):
#         if isinstance(obj,float) and (obj != obj):
#             return 'null'
#         return super().default(obj)



# # Step 1: Get unique tickers
# unique_tickers = prices_df['ticker'].unique()

# # Step 2: Create a dictionary to store the nested JSON structure
# data = []

# # Step 3: Iterate over the unique tickers
# for ticker in unique_tickers:
#     # Filter the DataFrame for the current ticker
#     ticker_data = prices_df[prices_df['ticker'] == ticker]

#     # Create a dictionary for each day
#     day_data = []
#     for _, row in ticker_data.iterrows():
#         day = {
#             "symbol": ticker,
#             "date": row['date'],
#             "dailyOpen": row['dailyOpen'],
#             "ask": row['ask'],
#             "bid": row['bid'],
#             "previousClose": row['previousClose'],
#             "dailyVolume": row['dailyVolume']
#         }
#         day_data.append(day)

#     # Create a dictionary for the ticker with nested day data
#     ticker_dict = {
#         "ticker": ticker,
#         "day": day_data
#     }

#     # Append the ticker dictionary to the data list
#     data.append(ticker_dict)

# # json cannot work with datetime dtypes: https://www.geeksforgeeks.org/how-to-fix-datetime-datetime-not-json-serializable-in-python/
# def serialize_dt(obj):
#     if isinstance(obj, dt.datetime):
#         return obj.isoformat()
#     raise TypeError("Type not serializable")

# json_data = json.dumps(data, indent=4, default = serialize_dt)
# with open("historical2.json", "w") as json_file:
#     json_file.write(json_data)

In [8]:
# historical_json = []
# grouped_tickers = prices_df.groupby(['ticker'])
# grouped_dates = prices_df.groupby(['date'])
# data = {
#     "tickers": list(grouped_tickers.groups.keys()),
#     "dates": list(grouped_dates.groups.keys()),
#     "history": []
# }

# for ticker, group in grouped_tickers:
#     ticker_data = {
#         "ticker": ticker,
#         "date": row['date']
#         "market": []
#     }

#     for date, day_group in group.groupby('date'):
#         date_data ={
#             "date": date,
#             # "symbol": row['ticker'],
#             "stats":[]
#         }
    
#         for index, row in day_group.iterrows():
#             entry_data = {
#                 # "symbol": row['ticker'],
#                 "date": row['date'],
#                 "datePrevClose": row['datePrevClose'],
#                 "dailyOpen": row['dailyOpen'],
#                 "dayHigh": row['dayHigh'],
#                 "dayLow": row['dayLow'],
#                 # "dailyClose": row['dailyClose'],
#                 "previousClose": row['previousClose'],
#                 "ask": row['ask'],
#                 "bid": row['bid'],
#                 "dailyVolume": row['dailyVolume']
#             }
#             date_data["market"].append(entry_data)
#         ticker_data["market"].append(date_data)
#     data["history"].append(ticker_data)
#     #     ticker_data["day"].append(day_data)
#     # data["days"].append(ticker_data)

# # json cannot work with datetime dtypes: https://www.geeksforgeeks.org/how-to-fix-datetime-datetime-not-json-serializable-in-python/
# def serialize_dt(obj):
#     if isinstance(obj, dt.datetime):
#         return obj.isoformat()
#     raise TypeError("Type not serializable")

# json_data = json.dumps(data, indent=4, default = serialize_dt)
# with open("historical.json", "w") as json_file:
#     json_file.write(json_data)

In [ ]:
#-----------
# Archive code below

In [9]:
## Old code-- delete later

# prices_df.to_json(
#     path_or_buf = 'all_prices_xdf.json',
#     orient = 'records',
#     date_format = 'iso')

# Old code - second attempt - delete later    json_file.write(json_data)



# Old code - delete later

#  THe follow is an attempt to reorganize the datafram into a structured json.  Then I realized it did not really matter
# json_data = {}

# for index, row in prices_df.iterrows():
#     date = row['date']
#     open = row['dailyOpen'], 
#     close = row['previousClose'], 
#     volume = row['dailyVolume'],
#     ticker = row['ticker'], 
#     cap = row['marketCap'], 
#     quick = row['quickRatio'],
#     sector = row['sector'],
#     low = row['52WeekLow'], 
#     high = row['52WeekHigh'], 
#     change = row['52WeekChange'],
#     ave_vol = row['10DayAverageVolume']

#     if date not in json_data:
#         json_data[date] = {'price':[],'info':[],'stats':[]}

#     json_data[date]['price'].append({'ticker':ticker,
#                                      'dailyOpen':open,
#                                      'previousClose':close,
#                                      'dailyVolume':volume
#                                                       })
#     json_data[date]['info'].append({'sector':sector,
#                                     'marketCap':cap,
#                                     })
#     json_data[date]['stats'].append({'52WeekLow':low,
#                                      '52WeekHigh':high, 
#                                      '52WeekChange': change,
#                                      '10DayAverageVolume':ave_vol
#                                      })
# # price_json = json.dumps(json_data)

# # pprint(price_json)

# prices = pd.DataFrame(json_data)
# prices.to_json('all_prices.json')


# Old code --  delet later

# Same commetn as previous cell

# output_path = f"{target_dir}/all_prices.json"

# with open('all_prices.json','w') as file:
#     file.write(price_json)